// Generates src/lib/api-schema.d.ts from the running sidecar's OpenAPI document.
//
//   npm run generate-api                     # uses http://127.0.0.1:8100
//   API_URL=http://127.0.0.1:8000 npm run generate-api
//
// The sidecar must be running:
//   uv run uvicorn api.server:app --host 127.0.0.1 --port 8100   (from the repo root)
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(here, '../src/lib/api-schema.d.ts')
const API_URL = process.env.API_URL ?? 'http://127.0.0.1:8100'
const SPEC_URL = `${API_URL.replace(/\/$/, '')}/openapi.json`

async function main() {
  process.stdout.write(`generate-api: reading ${SPEC_URL}\n`)
  let ast
  try {
    ast = await openapiTS(new URL(SPEC_URL))
  } catch (err) {
    process.stderr.write(
      `\ngenerate-api: could not read ${SPEC_URL}\n` +
        `Start the sidecar first:  uv run uvicorn api.server:app --host 127.0.0.1 --port 8100\n\n`,
    )
    throw err
  }
  const banner =
    '// AUTO-GENERATED by `npm run generate-api` from the sidecar /openapi.json.\n' +
    '// Do not edit by hand. Re-run after any api/schemas.py change.\n\n'
  writeFileSync(OUT, banner + astToString(ast), 'utf8')
  process.stdout.write(`generate-api: wrote ${OUT}\n`)
}

main().catch(() => process.exit(1))
